# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "boson"
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.6") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabriel Horner"]
  s.date = "2011-08-15"
  s.description = "Boson is a command/task framework with the power to turn any ruby method into a full-fledged executable with options.  Some unique features that differentiate it from rake and thor include being usable from irb and the commandline, optional automated views generated by hirb and allowing libraries to be written as plain ruby. For my libraries that use this, see irbfiles.  Works with all major ruby versions."
  s.email = "gabriel.horner@gmail.com"
  s.executables = ["boson"]
  s.extra_rdoc_files = ["README.rdoc", "LICENSE.txt"]
  s.files = ["bin/boson", "README.rdoc", "LICENSE.txt"]
  s.homepage = "http://tagaholic.me/boson/"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A command/task framework similar to rake and thor that opens your ruby universe to the commandline and irb."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hirb>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<alias>, [">= 0.2.2"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<bacon>, [">= 1.1.0"])
      s.add_development_dependency(%q<mocha-on-bacon>, [">= 0"])
      s.add_development_dependency(%q<bacon-bits>, [">= 0"])
    else
      s.add_dependency(%q<hirb>, [">= 0.5.0"])
      s.add_dependency(%q<alias>, [">= 0.2.2"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<bacon>, [">= 1.1.0"])
      s.add_dependency(%q<mocha-on-bacon>, [">= 0"])
      s.add_dependency(%q<bacon-bits>, [">= 0"])
    end
  else
    s.add_dependency(%q<hirb>, [">= 0.5.0"])
    s.add_dependency(%q<alias>, [">= 0.2.2"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<bacon>, [">= 1.1.0"])
    s.add_dependency(%q<mocha-on-bacon>, [">= 0"])
    s.add_dependency(%q<bacon-bits>, [">= 0"])
  end
end
