development:
  adapter: postgis
  host: localhost
  port: 5432
  username: postgres
  password:
  database: irekia_development
  encoding: utf8
  template: template_postgis

test:
  adapter: postgis
  host: localhost
  port: 5432
  username: postgres
  password:
  database: irekia_test
  encoding: utf8
  template: template_postgis
