development:
  adapter: postgresql
  encoding: unicode
  database: irekia_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  username: postgres
  password:
  database: irekia_test
  pool: 5
  encoding: unicode

production:
  adapter: postgresql
  username: postgres
  password:
  database: irekia_development
  pool: 5
  encoding: unicode
